name: course-management

on: [pull_request]    

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - name: build and run backend docker container
        run: docker build -t course-management . && docker run -d course-management
        working-directory: ${{env.working-directory}}
